### PR TITLE
Add Firefox Beta app icon, delete temporary files, and others

### PR DESCRIPTION
**Pull request by aminalhazwani**

### CODE REVIEW

**Comment by bwinton** [comment]
Should we also add that file to the `.gitignore` so that we don't accidentally check it in in the future?

**Comment by aminalhazwani** [comment]
Added!

**Comment by aminalhazwani** [comment]
Since this PR was still open I updated the title with the new changes, ping @bwinton

**Review by bwinton — APPROVED** [review]
Sure, seems good. :)

**Pull request merged**
